CREATE TABLE "PaymentProof" (
	"id" UUID NOT NULL UNIQUE,
	"quoteId" UUID NOT NULL,
	"url" TEXT NOT NULL,
	"isReviewed" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY ("id"),
	FOREIGN KEY ("quoteId") REFERENCES "Quote"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
