CREATE TABLE "AvailabilitySlot" (
	"id" UUID NOT NULL UNIQUE,
	"adminId" UUID NOT NULL,
	"startTime" TIMESTAMPTZ NOT NULL,
  "endTime" TIMESTAMPTZ NOT NULL,
	"isBooked" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id"),
	FOREIGN KEY("adminId") REFERENCES "users"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
