CREATE TABLE "QuoteImages" (
	"id" UUID NOT NULL UNIQUE,
	"quoteId" UUID NOT NULL,
	"url" TEXT NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY("quoteId") REFERENCES "Quote"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
